export const users = [
  {
    id: "1",
    email: "admin@okfashion.com",
    password: "$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    name: "Admin User",
    isAdmin: true,
  },
  {
    id: "2",
    email: "user@example.com",
    password: "$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
    name: "Demo User",
    isAdmin: false,
  },
]

export const mockRecommendations = [
  {
    id: "1",
    userId: "1",
    type: "outfit",
    title: "Professional Power Look",
    description: "Perfect for important meetings and presentations",
    category: "professional",
    confidence: 0.95,
    colors: ["#2C3E50", "#FFFFFF", "#E74C3C"],
    tags: ["Professional", "Confident", "Modern"],
    image: "/professional-outfit.jpg",
    createdAt: "2025-01-15T10:00:00Z",
    liked: false,
    saved: true,
  },
  {
    id: "2",
    userId: "1",
    type: "hairstyle",
    title: "Sleek Straight Hair",
    description: "Polished look that works for any occasion",
    category: "versatile",
    confidence: 0.88,
    colors: ["#8B4513"],
    tags: ["Sleek", "Professional", "Timeless"],
    image: "/sleek-hair.jpg",
    createdAt: "2025-01-15T09:30:00Z",
    liked: true,
    saved: false,
  },
  {
    id: "3",
    userId: "1",
    type: "color",
    title: "Spring Fresh Palette",
    description: "Light, fresh colors that brighten your complexion",
    category: "seasonal",
    confidence: 0.92,
    colors: ["#FFB6C1", "#98FB98", "#87CEEB", "#F0E68C"],
    tags: ["Fresh", "Light", "Youthful"],
    image: "/spring-palette.jpg",
    createdAt: "2025-01-15T09:00:00Z",
    liked: false,
    saved: true,
  },
]
